# syntax=docker/dockerfile:1

## Build
FROM docker.io/golang:1.19.2-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/dockerSample/main.go ./ 

RUN go build -o /GolangContainer

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /GolangContainer /GolangContainer

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/GolangContainer"]